name: Namma Thiruppur Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: Extract Android project
        run: |
          rm -rf build-project
          mkdir build-project
          unzip -q NammaThiruppur.zip -d build-project
          chmod -R u+rwX build-project
      - name: Build User App
        working-directory: build-project/NammaThiruppur
        run: |
          gradle :user-app:assembleDebug --no-daemon

      - name: Build Admin App
        working-directory: build-project/NammaThiruppur
        run: |
          gradle :admin-app:assembleDebug --no-daemon

      - name: Upload User App APK
        uses: actions/upload-artifact@v4
        with:
          name: Namma-Thiruppur-User-App
          path: build-project/NammaThiruppur/user-app/build/outputs/apk/debug/*.apk

      - name: Upload Admin App APK
        uses: actions/upload-artifact@v4
        with:
          name: Namma-Thiruppur-Admin-App
          path: build-project/NammaThiruppur/admin-app/build/outputs/apk/debug/*.apk
